# Generated by Django 6.0.5 on 2026-08-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivos',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
